// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sheets

import (
	"github.com/prongbang/analyticsgen/pkg/csvx"
)

// Injectors from wire.go:

func New() UseCase {
	callX := NewCallX()
	csvX := csvx.New()
	sheetsRepository := NewRepository(callX, csvX)
	sheetsUseCase := NewUseCase(sheetsRepository)
	return sheetsUseCase
}
