// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package analyticsgen

import (
	"github.com/prongbang/analyticsgen/internal/analyticsgen/generate"
	"github.com/prongbang/analyticsgen/internal/analyticsgen/sheets"
	"github.com/prongbang/filex"
)

// Injectors from wire.go:

func New() AnalyticsGen {
	fileX := filex.New()
	useCase := sheets.New()
	androidUseCase := generate.NewAndroidUseCase(useCase)
	flutterUseCase := generate.NewFlutterUseCase(useCase)
	iosUseCase := generate.NewIOSUseCase(useCase)
	analyticsgenAnalyticsGen := NewAnalyticsGen(fileX, androidUseCase, flutterUseCase, iosUseCase)
	return analyticsgenAnalyticsGen
}
